### ISSUE TITLE
JsonParseException if loading non existing module from a directory with invalid package.json

### ISSUE THREAD

**Issue by oberhamsi** [ringo/ringojs#204]
When I require a non existing module from a directory, which has a parent directory containing "package.json", I get a JsonParseException (see bottom). 

After fixing the package.json, I get "cannot find module" as I would have expected.

I would expect RingoJs to ignore a package.json, if it is invalid. Ringo could output a warning if run in --verbose.

```
java.lang.RuntimeException: org.mozilla.javascript.json.JsonParser$ParseException: Empty JSON string
at org.ringojs.engine.RhinoEngine.parseJsonResource(RhinoEngine.java:564)
at org.ringojs.engine.RhinoEngine.loadPackage(RhinoEngine.java:512)
at org.ringojs.engine.RhinoEngine.getScript(RhinoEngine.java:458)
at org.ringojs.engine.RingoWorker.loadModule(RingoWorker.java:257)
at org.ringojs.engine.Require.call(Require.java:84)
at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
at org.mozilla.javascript.gen._stdin__13._c_script_0(<stdin>:3)
at org.mozilla.javascript.gen._stdin__13.call(<stdin>)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
at org.mozilla.javascript.gen._stdin__13.call(<stdin>)
at org.mozilla.javascript.gen._stdin__13.exec(<stdin>)
at org.ringojs.engine.ReloadableScript.evaluate(ReloadableScript.java:186)
at org.ringojs.engine.RingoWorker.evaluateScript(RingoWorker.java:310)
at org.ringojs.tools.RingoShell.run(RingoShell.java:116)
at org.ringojs.tools.RingoRunner.run(RingoRunner.java:165)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.ringojs.tools.launcher.Main.run(Main.java:66)
at org.ringojs.tools.launcher.Main.main(Main.java:45)
Caused by: org.mozilla.javascript.json.JsonParser$ParseException: Empty JSON string
at org.mozilla.javascript.json.JsonParser.readValue(JsonParser.java:85)
at org.mozilla.javascript.json.JsonParser.parseValue(JsonParser.java:44)
at org.ringojs.engine.RhinoEngine.parseJsonResource(RhinoEngine.java:557)
```

**Comment by oberhamsi** [comment]
hasn't come up again
