### ISSUE TITLE
! is treated as special character by jline console

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#312]
Start the ringo command line and try to create a string with a `!` at the end:

```
>> var ba = "hello world!".toByteArray("UTF-8");
[ERROR] Could not expand event
java.lang.IllegalArgumentException: !".toByteArray("UTF-8");: event not found
	at jline.console.ConsoleReader.expandEvents(ConsoleReader.java:779)
	at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:631)
	at jline.console.ConsoleReader.accept(ConsoleReader.java:2019)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2666)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
	at org.ringojs.tools.RingoShell.run(RingoShell.java:99)
	at org.ringojs.tools.RingoRunner.run(RingoRunner.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.ringojs.tools.launcher.Main.run(Main.java:66)
	at org.ringojs.tools.launcher.Main.main(Main.java:45)
```

**Comment by grob** [comment]
Good catch, thanks!

**Comment by botic** [comment]
Thx, will ship with 0.12!
