### ISSUE TITLE
RingoJS not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by mpsaavedra** [ringo/ringojs#402]
every time i try to execute RingoJS in my computer i get this error

Uncaught exception: 
java.lang.NullPointerException
	at org.ringojs.tools.launcher.Main.getRingoHome(Main.java:169)
	at org.ringojs.tools.launcher.Main.<init>(Main.java:50)
	at org.ringojs.tools.launcher.Main.main(Main.java:44)

uname -a
Linux working-laptop 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Java --version

openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

**Comment by botic** [comment]
Where is your `RINGO_HOME` environment variable pointing to? Or do you have a `ringo.home` Java property set? If not set, Ringo tries to use the location of the `Main` class as `RINGO_HOME`. Since a lot of the class loading process has been changed with Java 9+ there might be the root issue.

Are you using RingoJS 1.2.1 or master?
