### ISSUE TITLE
RINGO_HOME not detected in macOS 11.2 

### ISSUE THREAD

**Issue by botic** [ringo/ringojs#417]
Beginning with macOS 11.2 I cannot start Ringo without explictly setting `RINGO_HOME`. It worked before, so my guess is that `function find_ringo_home()` is not working anymore with zsh / macOS Terminal.

Example:

```
philipp@PNP-MBP-2 someproject % ringo -v
home /Users/philipp/Code/someproject
```

This should output `home /Users/philipp/Code/ringojs` instead, but `RINGO_HOME` always points to the current working directory.

**Comment by botic** [comment]
It's a bug related to Java 11:

```
~ > java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)

~ > ringo
... works as expected

~ > jdk 11

~ > java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

~ > ringo
Uncaught exception:
java.lang.IllegalArgumentException: Directory '/Users/philipp/lib' does not exist
	at org.ringojs.tools.launcher.RingoClassLoader.addClasspathWildcard(RingoClassLoader.java:65)
	at org.ringojs.tools.launcher.RingoClassLoader.<init>(RingoClassLoader.java:47)
	at org.ringojs.tools.launcher.Main.createClassLoader(Main.java:131)
	at org.ringojs.tools.launcher.Main.<init>(Main.java:51)
	at org.ringojs.tools.launcher.Main.main(Main.java:44)

```

**Comment by botic** [comment]
After some debugging, I see a different output in `Main.getRingoHome()` Java 11 and Java 8:

**Java 8:**
```
Code > ringo -v
Home: /Users/philipp/Code/ringojs / /Users/philipp/Code/ringojs
```

**Java 11:**
```
Code > ringo -v
Home: . / /Users/philipp/Code
```

The reason are the changes in the classloader hierarchie. In Java 8 the system classloader is an `URLClassLoader`, but starting with Java 9 this (unspecified) behavior changed.
